services:
  mysql:
    image: mysql:8.0
    restart: ${RESTART_POLICY:-unless-stopped}
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-helpdesk}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-fubar}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:${MYSQL_PORT:-3306}:3306"
    networks:
      - network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_ROOT_PASSWORD:-fubar}",
        ]
      interval: 10s # Aumenta o intervalo entre as verificações

      timeout: 5s
      retries: 10 # Aumenta o número de tentativas antes de considerar o serviço como não saudável
      start_period: 30s # Dá um tempo adicional para o MySQL inicializar

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    env_file: .env
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - ./api:/app
      - node_modules_api:/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    env_file: .env
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${WEB_PORT:-5173}:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - network

volumes:
  node_modules_api:
  node_modules_web:
  mysql:

networks:
  network:
    name: ${COMPOSE_PROJECT_NAME:-helpdesk}
